Integrate today-log into today

diff --git a/today b/today
--- a/today
+++ b/today
@@ -6,8 +6,9 @@ set -eu
 
 usage() {
 	name="${0##*/}"
-	printf 'Usage: %s [[[YYYY-]MM-]DD] ...\n' "$name"
+	printf 'Usage: %s [[[YYYY-]MM-]DD]\n' "$name"
 	printf '       %s grep ARGUMENT ...\n' "$name"
+	printf '       %s log [-v]\n' "$name"
 	printf '       %s -h\n' "$name"
 }
 
@@ -73,28 +74,22 @@ valid_date_file() {
 	}'
 }
 
-dates_to_files() {
-	filenames=''
-	while [ "$#" -gt 0 ]
-	do
-		[ -n "$1" ] || continue
-		filename=$(date_file "$(expand_date "$1")")
-		filename=$(printf '%s\n' "$filename" | valid_date_file)
-		if [ -n "$filename" ]
-		then
-			filenames=$(printf '%s\n%s' "$filenames" "$filename")
-		else
-			printf 'Invalid date: %s\n' "$1" >&2
-			return 2
-		fi
-		shift
-	done
-	printf '%s' "$filenames" | sort
-}
-
 edit_file() {
-	mkdir -p "${1%/*}"
-	TODAY_FILE="$1"
+	if [ "$#" -gt 1 ]
+	then
+		printf 'Too many arguments\n' >&2
+		usage >&2
+		return 2
+	fi
+	filename=$(date_file "$(expand_date "$1")" | valid_date_file)
+	if [ -z "$filename" ]
+	then
+		printf 'Invalid date: %s\n' "$1" >&2
+		usage >&2
+		return 2
+	fi
+	mkdir -p "${filename%/*}"
+	TODAY_FILE="$filename"
 	# shellcheck disable=SC2034
 	TODAY_TODO=$(todo_file)
 	set +e
@@ -105,7 +100,6 @@ edit_file() {
 	then
 		rm -f "$TODAY_FILE"
 	fi
-	unset -v TODAY_FILE TODAY_TODO
 }
 
 search_files() {
@@ -113,7 +107,43 @@ search_files() {
 }
 
 view_files() {
-	cat "$@" | ${PAGER:-more}
+	case "$#" in
+		0)
+			sort_args='-r'
+			;;
+		1)
+			if [ "$1" = '-v' ]
+			then
+				sort_args=
+			else
+				printf 'Invalid option to log: %s\n' "$1" >&2
+				usage >&2
+				return 2
+			fi
+			;;
+		*)
+			printf 'Too many options to log\n' >&2
+			usage >&2
+			return 2
+			;;
+	esac
+	pat="[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$TODAY_SUFFIX"
+	find "$TODAY_DIR" -type f -name "$pat" | sort "$sort_args" |
+		while IFS= read -r f
+	do
+		printf '%s\n\n' "$(basename "$f" "$TODAY_SUFFIX")"
+		cat "$f"
+		printf '\n\n\n'
+	done | pager_if_terminal
+}
+
+pager_if_terminal() {
+	if [ -t 1 ]
+	then
+		${PAGER:-more}
+	else
+		cat
+	fi
 }
 
 
@@ -133,24 +163,14 @@ case "$1" in
 		shift
 		search_files "$@"
 		;;
+	log)
+		shift
+		view_files "$@"
+		;;
 	-h)
 		usage
 		;;
 	*)
-		# shellcheck disable=SC2046
-		set -- $(dates_to_files "$@")
-		case "$#" in
-			0)
-				# Invalid date argument.
-				usage >&2
-				exit 2
-				;;
-			1)
-				edit_file "$1"
-				;;
-			*)
-				view_files "$@"
-				;;
-		esac
+		edit_file "$@"
 		;;
 esac
